// Lista completa de vídeos do portfólio baseada no arquivo pasted_content.txt
export const portfolioVideos = [
  {
    title: "AWA Comercial",
    category: "Institucional",
    description: "Filme institucional da AWA Comercial apresentando a empresa e seus valores.",
    image: "https://i.ytimg.com/vi/6bseD2wgI6A/maxresdefault.jpg",
    videoId: "6bseD2wgI6A",
  },
  {
    title: "Ecoparque",
    category: "Ação de Marketing",
    description: "Ação de marketing do Ecoparque destacando sustentabilidade e inovação.",
    image: "https://i.ytimg.com/vi/J3KO2lBBh-w/maxresdefault.jpg",
    videoId: "J3KO2lBBh-w",
  },
  {
    title: "Unifateb",
    category: "Institucional",
    description: "Apresentação institucional da Unifateb e seus cursos.",
    image: "https://i.ytimg.com/vi/Wyg3UPuf5Ec/maxresdefault.jpg",
    videoId: "Wyg3UPuf5Ec",
  },
  {
    title: "BluePrism",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo BluePrism.",
    image: "https://i.ytimg.com/vi/carUjyho6cc/maxresdefault.jpg",
    videoId: "carUjyho6cc",
  },
  {
    title: "Favretto Mídia Exterior - Elevador",
    category: "Produto",
    description: "Apresentação do produto elevador da Favretto Mídia Exterior.",
    image: "https://i.ytimg.com/vi/YU1VTsr-h-Q/maxresdefault.jpg",
    videoId: "YU1VTsr-h-Q",
  },
  {
    title: "Ditrator",
    category: "Institucional",
    description: "Filme institucional da Ditrator.",
    image: "https://i.ytimg.com/vi/AO4UycrhPMM/maxresdefault.jpg",
    videoId: "AO4UycrhPMM",
  },
  {
    title: "Favretto Mídia Exterior - Circuito Digital",
    category: "Produto",
    description: "Apresentação do circuito digital da Favretto Mídia Exterior.",
    image: "https://i.ytimg.com/vi/ijhaceaSY94/maxresdefault.jpg",
    videoId: "ijhaceaSY94",
  },
  {
    title: "Favretto Mídia Exterior - Pedágio",
    category: "Produto",
    description: "Apresentação do produto pedágio da Favretto Mídia Exterior.",
    image: "https://i.ytimg.com/vi/MTFaQK6quaM/maxresdefault.jpg",
    videoId: "MTFaQK6quaM",
  },
  {
    title: "Spaten",
    category: "Ação de Marketing",
    description: "Ação de marketing da cerveja Spaten.",
    image: "https://i.ytimg.com/vi/1MiPQ-J36rE/maxresdefault.jpg",
    videoId: "1MiPQ-J36rE",
  },
  {
    title: "E.Mix",
    category: "Case",
    description: "Case de sucesso da E.Mix.",
    image: "https://i.ytimg.com/vi/VBOcex5L9-Y/maxresdefault.jpg",
    videoId: "VBOcex5L9-Y",
  },
  {
    title: "CW Trends",
    category: "Conteúdo",
    description: "Conteúdo produzido para CW Trends.",
    image: "https://i.ytimg.com/vi/oSOtzDN-Z24/maxresdefault.jpg",
    videoId: "oSOtzDN-Z24",
  },
  {
    title: "Minha Biblioteca Católica",
    category: "Ação de Marketing",
    description: "Ação de marketing da Minha Biblioteca Católica.",
    image: "https://i.ytimg.com/vi/RRp3Kqn9dcw/maxresdefault.jpg",
    videoId: "RRp3Kqn9dcw",
  },
  {
    title: "DentalUni",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo DentalUni.",
    image: "https://i.ytimg.com/vi/7dyfktBB9wA/maxresdefault.jpg",
    videoId: "7dyfktBB9wA",
  },
  {
    title: "Mercedes-Benz",
    category: "Institucional",
    description: "Filme institucional da Mercedes-Benz.",
    image: "https://i.ytimg.com/vi/kKpIG1XKbS0/maxresdefault.jpg",
    videoId: "kKpIG1XKbS0",
  },
  {
    title: "Liquexpress",
    category: "Institucional",
    description: "Filme institucional da Liquexpress.",
    image: "https://i.ytimg.com/vi/Dvj_JDpJPTU/maxresdefault.jpg",
    videoId: "Dvj_JDpJPTU",
  },
  {
    title: "NineTwo Performance",
    category: "Conteúdo",
    description: "Conteúdo produzido para NineTwo Performance.",
    image: "https://i.ytimg.com/vi/vcCr_Kbn8Nw/maxresdefault.jpg",
    videoId: "vcCr_Kbn8Nw",
  },
  {
    title: "Biofarm",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo Biofarm.",
    image: "https://i.ytimg.com/vi/NIr6l2d-iug/maxresdefault.jpg",
    videoId: "NIr6l2d-iug",
  },
  {
    title: "Favretto Mídia Exterior - Top Front",
    category: "Produto",
    description: "Apresentação do produto Top Front da Favretto Mídia Exterior.",
    image: "https://i.ytimg.com/vi/HyK3vy4dgaI/maxresdefault.jpg",
    videoId: "HyK3vy4dgaI",
  },
  {
    title: "Paraná Clínicas",
    category: "Institucional",
    description: "Filme institucional da Paraná Clínicas.",
    image: "https://i.ytimg.com/vi/odE0fqvvWa8/maxresdefault.jpg",
    videoId: "odE0fqvvWa8",
  },
  {
    title: "Escolar Office Brasil",
    category: "Case",
    description: "Case de sucesso da Escolar Office Brasil.",
    image: "https://i.ytimg.com/vi/YjST4vR4hfY/maxresdefault.jpg",
    videoId: "YjST4vR4hfY",
  },
  {
    title: "Pasa",
    category: "Treinamento",
    description: "Vídeo de treinamento da Pasa.",
    image: "https://i.ytimg.com/vi/cUatyp4eyhw/maxresdefault.jpg",
    videoId: "cUatyp4eyhw",
  },
  {
    title: "Novartis",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo Novartis.",
    image: "https://i.ytimg.com/vi/p9MGzLy35lE/maxresdefault.jpg",
    videoId: "p9MGzLy35lE",
  },
  {
    title: "LJ Santos - Linha de Cromagem",
    category: "Produto",
    description: "Apresentação da linha de cromagem da LJ Santos.",
    image: "https://i.ytimg.com/vi/hELpTXBl798/maxresdefault.jpg",
    videoId: "hELpTXBl798",
  },
  {
    title: "DentalUni 2",
    category: "Evento Corporativo",
    description: "Segunda cobertura do evento corporativo DentalUni.",
    image: "https://i.ytimg.com/vi/0dVNlYTni_o/maxresdefault.jpg",
    videoId: "0dVNlYTni_o",
  },
  {
    title: "BioBio",
    category: "Produto",
    description: "Apresentação de produto da BioBio.",
    image: "https://i.ytimg.com/vi/-ubKHgwhJEU/maxresdefault.jpg",
    videoId: "-ubKHgwhJEU",
  },
  {
    title: "BluePrism",
    category: "Evento Corporativo",
    description: "Segunda cobertura do evento corporativo BluePrism.",
    image: "https://i.ytimg.com/vi/3YNyHv8jH60/maxresdefault.jpg",
    videoId: "3YNyHv8jH60",
  },
  {
    title: "Escolar Office Brasil",
    category: "Case",
    description: "Segundo case de sucesso da Escolar Office Brasil.",
    image: "https://i.ytimg.com/vi/rGk75VaxOHA/maxresdefault.jpg",
    videoId: "rGk75VaxOHA",
  },
  {
    title: "Construtora Equilíbrio",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo da Construtora Equilíbrio.",
    image: "https://i.ytimg.com/vi/ipRxXf7od5E/maxresdefault.jpg",
    videoId: "ipRxXf7od5E",
  },
  {
    title: "ENAF",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo ENAF.",
    image: "https://i.ytimg.com/vi/NSaibgM86dY/maxresdefault.jpg",
    videoId: "NSaibgM86dY",
  },
  {
    title: "Lumicenter",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo Lumicenter.",
    image: "https://i.ytimg.com/vi/ond_kR7F_7s/maxresdefault.jpg",
    videoId: "ond_kR7F_7s",
  },
  {
    title: "LJ Santos",
    category: "Institucional",
    description: "Filme institucional da LJ Santos.",
    image: "https://i.ytimg.com/vi/Qjciy6xLVsk/maxresdefault.jpg",
    videoId: "Qjciy6xLVsk",
  },
  {
    title: "Congemas",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo Congemas.",
    image: "https://i.ytimg.com/vi/Dm7kuEJ-McY/maxresdefault.jpg",
    videoId: "Dm7kuEJ-McY",
  },
  {
    title: "Dufrio",
    category: "Produto",
    description: "Apresentação de produto da Dufrio.",
    image: "https://i.ytimg.com/vi/eGiFbkpiH0Q/maxresdefault.jpg",
    videoId: "eGiFbkpiH0Q",
  },
  {
    title: "LJ Santos - Feira",
    category: "Evento Corporativo",
    description: "Cobertura da feira da LJ Santos.",
    image: "https://i.ytimg.com/vi/foKTC-e29w8/maxresdefault.jpg",
    videoId: "foKTC-e29w8",
  },
  {
    title: "Action COACH",
    category: "Institucional",
    description: "Filme institucional da Action COACH.",
    image: "https://i.ytimg.com/vi/Roo1OWxkCZM/maxresdefault.jpg",
    videoId: "Roo1OWxkCZM",
  },
  {
    title: "Motin Films",
    category: "Produto",
    description: "Apresentação da própria Motin Films.",
    image: "https://i.ytimg.com/vi/oD1ITLt8SP4/maxresdefault.jpg",
    videoId: "oD1ITLt8SP4",
  },
  {
    title: "Compwire",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo Compwire.",
    image: "https://i.ytimg.com/vi/zHyHZ2QnBjg/maxresdefault.jpg",
    videoId: "zHyHZ2QnBjg",
  },
  {
    title: "Hogrefe Construtora",
    category: "Produto",
    description: "Apresentação de produto da Hogrefe Construtora.",
    image: "https://i.ytimg.com/vi/C4V_BwMlKE0/maxresdefault.jpg",
    videoId: "C4V_BwMlKE0",
  },
  {
    title: "Francal Feiras",
    category: "Ação de Marketing",
    description: "Ação de marketing da Francal Feiras.",
    image: "https://i.ytimg.com/vi/WMFSuFo6iAA/maxresdefault.jpg",
    videoId: "WMFSuFo6iAA",
  },
  {
    title: "Flash Construtora",
    category: "Produto",
    description: "Apresentação de produto da Flash Construtora.",
    image: "https://i.ytimg.com/vi/67FQ4Isw2tM/maxresdefault.jpg",
    videoId: "67FQ4Isw2tM",
  },
  {
    title: "Händz",
    category: "Produto",
    description: "Apresentação de produto da Händz.",
    image: "https://i.ytimg.com/vi/oC-T7m3JU8E/maxresdefault.jpg",
    videoId: "oC-T7m3JU8E",
  },
  {
    title: "LJ Santos 2",
    category: "Produto",
    description: "Segunda apresentação de produto da LJ Santos.",
    image: "https://i.ytimg.com/vi/4LE6PpXeUnQ/maxresdefault.jpg",
    videoId: "4LE6PpXeUnQ",
  },
  {
    title: "CW Trends ",
    category: "Institucional",
    description: "Filme institucional da CW Trends.",
    image: "https://i.ytimg.com/vi/XHPNutOOTQo/maxresdefault.jpg",
    videoId: "XHPNutOOTQo",
  },
  {
    title: "Naport",
    category: "Produto",
    description: "Apresentação de produto da Naport.",
    image: "https://i.ytimg.com/vi/LgXxgTIMjmY/maxresdefault.jpg",
    videoId: "LgXxgTIMjmY",
  },
  {
    title: "Compwire ",
    category: "Case",
    description: "Case de sucesso da Compwire.",
    image: "https://i.ytimg.com/vi/ENuvzngBuK4/maxresdefault.jpg",
    videoId: "ENuvzngBuK4",
  },
  {
    title: "PesadosWEB",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo PesadosWEB.",
    image: "https://i.ytimg.com/vi/rQci5PHwSAA/maxresdefault.jpg",
    videoId: "rQci5PHwSAA",
  },
  {
    title: "Vila Yamon",
    category: "Institucional",
    description: "Filme institucional da Vila Yamon.",
    image: "https://i.ytimg.com/vi/JjBw2zdNuek/maxresdefault.jpg",
    videoId: "JjBw2zdNuek",
  },
  {
    title: "Thiago Castelli",
    category: "Artistas",
    description: "Produção para o artista Thiago Castelli.",
    image: "https://i.ytimg.com/vi/5xTvnW6of2o/maxresdefault.jpg",
    videoId: "5xTvnW6of2o",
  },
  {
    title: "CW Trends ",
    category: "Ação de Marketing",
    description: "Ação de marketing da CW Trends.",
    image: "https://i.ytimg.com/vi/2r1PhYSU5hY/maxresdefault.jpg",
    videoId: "2r1PhYSU5hY",
  },
  {
    title: "Ruan Mansur",
    category: "Artistas",
    description: "Produção para o artista Ruan Mansur.",
    image: "https://i.ytimg.com/vi/N_Lj-2hQIZc/maxresdefault.jpg",
    videoId: "N_Lj-2hQIZc",
  },
  {
    title: "Thiago Castelli ",
    category: "Artistas",
    description: "Segunda produção para o artista Thiago Castelli.",
    image: "https://i.ytimg.com/vi/qy5XkX6wrwg/maxresdefault.jpg",
    videoId: "qy5XkX6wrwg",
  },
  {
    title: "Fresno",
    category: "Artistas",
    description: "Produção para a banda Fresno.",
    image: "https://i.ytimg.com/vi/2VcVx8T93cY/maxresdefault.jpg",
    videoId: "2VcVx8T93cY",
  },
  {
    title: "Action Coach ",
    category: "Conteúdo",
    description: "Conteúdo produzido para Action Coach.",
    image: "https://i.ytimg.com/vi/XauRtG4ALys/maxresdefault.jpg",
    videoId: "XauRtG4ALys",
  },
  {
    title: "DJ CZ",
    category: "Artistas",
    description: "Produção para o DJ CZ.",
    image: "https://i.ytimg.com/vi/Te02nXKzfOA/maxresdefault.jpg",
    videoId: "Te02nXKzfOA",
  },
  {
    title: "The Batman",
    category: "Ação de Marketing",
    description: "Ação de marketing do filme The Batman.",
    image: "https://i.ytimg.com/vi/3VHmQY5Ak90/maxresdefault.jpg",
    videoId: "3VHmQY5Ak90",
  },
  {
    title: "Shot Time",
    category: "Ação de Marketing",
    description: "Ação de marketing da Shot Time.",
    image: "https://i.ytimg.com/vi/pavAz8vN4DY/maxresdefault.jpg",
    videoId: "pavAz8vN4DY",
  },
  {
    title: "Ruan Mansur ",
    category: "Artistas",
    description: "Segunda produção para o artista Ruan Mansur.",
    image: "https://i.ytimg.com/vi/QQYqNDKLaQs/maxresdefault.jpg",
    videoId: "QQYqNDKLaQs",
  },
  {
    title: "CW Trends ",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo CW Trends.",
    image: "https://i.ytimg.com/vi/AZ40lXILG2Q/maxresdefault.jpg",
    videoId: "AZ40lXILG2Q",
  },
  {
    title: "CW Trends ",
    category: "Ação de Marketing",
    description: "Segunda ação de marketing da CW Trends.",
    image: "https://i.ytimg.com/vi/zH3rERJkmRI/maxresdefault.jpg",
    videoId: "zH3rERJkmRI",
  },
  {
    title: "Ghostbusters",
    category: "Ação de Marketing",
    description: "Ação de marketing do filme Ghostbusters.",
    image: "https://i.ytimg.com/vi/0-CXPK2MlWI/maxresdefault.jpg",
    videoId: "0-CXPK2MlWI",
  },
  {
    title: "Favretto Mídia Exterior 2",
    category: "Produto",
    description: "Segunda apresentação de produto da Favretto Mídia Exterior.",
    image: "https://i.ytimg.com/vi/-afHOczVR38/maxresdefault.jpg",
    videoId: "-afHOczVR38",
  },
  {
    title: "Gards",
    category: "Institucional",
    description: "Filme institucional da Gards.",
    image: "https://i.ytimg.com/vi/5_nDj1d2tyw/maxresdefault.jpg",
    videoId: "5_nDj1d2tyw",
  },
  {
    title: "Motin Films ",
    category: "Produto",
    description: "Segunda apresentação da própria Motin Films.",
    image: "https://i.ytimg.com/vi/eBuo2rlB9mo/maxresdefault.jpg",
    videoId: "eBuo2rlB9mo",
  }
];

export const categories = [
  "Todos",
  "Institucional", 
  "Evento Corporativo",
  "Produto",
  "Case",
  "Conteúdo",
  "Ação de Marketing",
  "Artistas",
  "Treinamento"
];

