// Lista completa de vídeos do portfólio baseada no arquivo pasted_content.txt
export const portfolioVideos = [
  {
    title: "AWA Comercial",
    category: "Institucional",
    description: "Filme institucional para a AWA Comercial, referência nacional na fabricação e distribuição de produtos em aço para o setor da construção civil.",
    image: "https://i.ytimg.com/vi/6bseD2wgI6A/maxresdefault.jpg",
    videoId: "6bseD2wgI6A",
  },
  {
    title: "Ecoparque",
    category: "Ação de Marketing",
    description: "Filme promocional com influenciadoras para divulgar o Ecoparque, bairro integrado e sustentável em Cascavel (PR)",
    image: "https://i.ytimg.com/vi/J3KO2lBBh-w/maxresdefault.jpg",
    videoId: "J3KO2lBBh-w",
  },
  {
    title: "Unifateb",
    category: "Institucional",
    description: "Filme institucional produzido para a Unifateb e o Colégio Dom Bosco, instituições que há mais de duas décadas impulsionam o desenvolvimento educacional de Telêmaco Borba e região.",
    image: "https://i.ytimg.com/vi/Wyg3UPuf5Ec/maxresdefault.jpg",
    videoId: "Wyg3UPuf5Ec",
  },
  {
    title: "SS&C BluePrism | Buenos Aires",
    category: "Evento Corporativo",
    description: "Cobertura do evento exclusivo da SS&C Blue Prism na Argentina que reuniu líderes para debater o futuro da automação de processos.",
    image: "https://i.ytimg.com/vi/carUjyho6cc/maxresdefault.jpg",
    videoId: "carUjyho6cc",
  },
  {
    title: "Favretto Mídia Exterior | Elevador",
    category: "Produto",
    description: "Filme produzido para a Favretto Mídia Exterior, apresentando seu mais novo produto que leva publicidade para elevadores comerciais e residenciais.",
    image: "https://i.ytimg.com/vi/YU1VTsr-h-Q/maxresdefault.jpg",
    videoId: "YU1VTsr-h-Q",
  },
  {
    title: "Ditrator",
    category: "Institucional",
    description: "Filme institucional produzido para a Ditrator, distribuidora de peças para tratores agrícolas e motores a diesel com mais de 30 anos de história.",
    image: "https://i.ytimg.com/vi/AO4UycrhPMM/maxresdefault.jpg",
    videoId: "AO4UycrhPMM",
  },
  {
    title: "Favretto Mídia Exterior | Circuito Digital",
    category: "Produto",
    description: "Filme produzido para a Favretto Mídia Exterior, divulgando seu Circuito Digital, produto que conecta marcas e pessoas através de painéis digitais espalhados por Curitiba.",
    image: "https://i.ytimg.com/vi/ijhaceaSY94/maxresdefault.jpg",
    videoId: "ijhaceaSY94",
  },
  {
    title: "Favretto Mídia Exterior | LED Pedágio",
    category: "Produto",
    description: "Filme produzido para a Favretto Mídia Exterior, divulgando o LED Pedágio, produto com 8 telas simultâneas, localizado na BR-101, em Santa Catarina.",
    image: "https://i.ytimg.com/vi/MTFaQK6quaM/maxresdefault.jpg",
    videoId: "MTFaQK6quaM",
  },
  {
    title: "Spaten",
    category: "Ação de Marketing",
    description: "Filme produzido pela Spaten para divulgação de uma ação de marketing em diversos bares de Curitiba durante o St. Patrick's Day.",
    image: "https://i.ytimg.com/vi/1MiPQ-J36rE/maxresdefault.jpg",
    videoId: "1MiPQ-J36rE",
  },
  {
    title: "E.Mix",
    category: "Case",
    description: "Filme case com depoimentos do Grupo Positivo sobre a implementação dos softwares de automação para comércio exterior e logística da e.Mix.",
    image: "https://i.ytimg.com/vi/VBOcex5L9-Y/maxresdefault.jpg",
    videoId: "VBOcex5L9-Y",
  },
  {
    title: "CW Trends",
    category: "Conteúdo",
    description: "Filme conteúdo sobre a diferença entre creatina monohidratada e Creapure para a CWTrends, loja de suplementos localizada em Curitiba.",
    image: "https://i.ytimg.com/vi/oSOtzDN-Z24/maxresdefault.jpg",
    videoId: "oSOtzDN-Z24",
  },
  {
    title: "Minha Biblioteca Católica",
    category: "Ação de Marketing",
    description: "Filme criado para a Minha Biblioteca Católica, como parte da campanha \"Esqueça um Livro\", que espalha mensagens de fé e esperança pelo país.",
    image: "https://i.ytimg.com/vi/RRp3Kqn9dcw/maxresdefault.jpg",
    videoId: "RRp3Kqn9dcw",
  },
  {
    title: "DentalUni | 14º Workshop DentalUni",
    category: "Evento Corporativo",
    description: "Cobertura do 14º Workshop DentalUni, realizado em Curitiba e que reuniu mais de 400 profissionais de odontologia de todo o Paraná.",
    image: "https://i.ytimg.com/vi/7dyfktBB9wA/maxresdefault.jpg",
    videoId: "7dyfktBB9wA",
  },
  {
    title: "Mercedes-Benz",
    category: "Institucional",
    description: "Filme institucional produzido para a Mercedes-Benz, focando na sua linha de caminhões extra-pesados e reforçando sua posição como uma das maiores fabricantes do mundo.",
    image: "https://i.ytimg.com/vi/kKpIG1XKbS0/maxresdefault.jpg",
    videoId: "kKpIG1XKbS0",
  },
  {
    title: "Liquexpress",
    category: "Institucional",
    description: "Filme institucional produzido para a Liquexpress, empresa líder em transporte e logística de cargas perigosas em todo o Sul do Brasil.",
    image: "https://i.ytimg.com/vi/Dvj_JDpJPTU/maxresdefault.jpg",
    videoId: "Dvj_JDpJPTU",
  },
  {
    title: "NineTwo Performance",
    category: "Conteúdo",
    description: "Filme conteúdo sobre KPIs desenvolvido para a NineTwo Performance, empresa focada em marketing, dados e tecnologia.",
    image: "https://i.ytimg.com/vi/vcCr_Kbn8Nw/maxresdefault.jpg",
    videoId: "vcCr_Kbn8Nw",
  },
  {
    title: "Biofarm | Agroleite 2024",
    category: "Evento Corporativo",
    description: "Filme para a Biofarm, líder em medicamentos veterinários, sobre o lançamento de sua nova solução para o tratamento de parasitas em bovinos durante a Agroleite 2024.",
    image: "https://i.ytimg.com/vi/NIr6l2d-iug/maxresdefault.jpg",
    videoId: "NIr6l2d-iug",
  },
  {
    title: "Favretto Mídia Exterior | Top Front",
    category: "Produto",
    description: "Filme produzido para a Favretto Mídia Exterior, divulgando sua linha de Top Fronts, solução OOH com milhões de impactos diários em Curitiba.",
    image: "https://i.ytimg.com/vi/HyK3vy4dgaI/maxresdefault.jpg",
    videoId: "HyK3vy4dgaI",
  },
  {
    title: "Paraná Clínicas",
    category: "Institucional",
    description: "Filme institucional produzido para a Paraná Clínicas, empresa especializada em planos médicos empresariais em Curitiba e Região Metropolitana há mais de 50 anos.",
    image: "https://i.ytimg.com/vi/odE0fqvvWa8/maxresdefault.jpg",
    videoId: "odE0fqvvWa8",
  },
  {
    title: "Escolar Office Brasil | Master Paper",
    category: "Case",
    description: "Filme produzido para a Escolar Office Brasil, parte da série \"Escolar pelo Brasil\", acompanhando a rotina e a história da papelaria Master Paper em Florianópolis.",
    image: "https://i.ytimg.com/vi/YjST4vR4hfY/maxresdefault.jpg",
    videoId: "YjST4vR4hfY",
  },
  {
    title: "Pasa | Operador de shiploader",
    category: "Treinamento",
    description: "Filme produzido para o treinamento de operador de shiploader da Pasa, empresa portuária de Paranaguá especializada no embarque de açúcar a granel no Sul do país.",
    image: "https://i.ytimg.com/vi/cUatyp4eyhw/maxresdefault.jpg",
    videoId: "cUatyp4eyhw",
  },
  {
    title: "Novartis | IluminarHS",
    category: "Evento Corporativo",
    description: "Cobertura do evento corporativo IluminarHS do Grupo Novartis, empresa global de cuidados com a saúde focada em medicamentos inovadores.",
    image: "https://i.ytimg.com/vi/p9MGzLy35lE/maxresdefault.jpg",
    videoId: "p9MGzLy35lE",
  },
  {
    title: "LJ Santos | Linha de Cromagem",
    category: "Produto",
    description: "Filme produzido para a LJ Santos, destacando sua linha de cromagem, projetada para garantir o acabamento impecável de peças plásticas para o setor automobilístico.",
    image: "https://i.ytimg.com/vi/hELpTXBl798/maxresdefault.jpg",
    videoId: "hELpTXBl798",
  },
  {
    title: "DentalUni | Connect Week Summit",
    category: "Evento Corporativo",
    description: "Filme corporativo sobre a participação da DentalUni na Connect Week Summit, um dos maiores festivais de inovação e tecnologia do Brasil.",
    image: "https://i.ytimg.com/vi/0dVNlYTni_o/maxresdefault.jpg",
    videoId: "0dVNlYTni_o",
  },
  {
    title: "BioBio | Only One",
    category: "Produto",
    description: "Filme produzido para a Biobio Cosméticos, divulgando sua linha de séruns Only One.",
    image: "https://i.ytimg.com/vi/-ubKHgwhJEU/maxresdefault.jpg",
    videoId: "-ubKHgwhJEU",
  },
  {
    title: "SS&C BluePrism | Live São Paulo",
    category: "Evento Corporativo",
    description: "Filme produzido para o SS&C Blue Prism Live São Paulo, evento exclusivo que destacou a inovação e o impacto da empresa global líder em automação de processos robóticos.",
    image: "https://i.ytimg.com/vi/3YNyHv8jH60/maxresdefault.jpg",
    videoId: "3YNyHv8jH60",
  },
  {
    title: "Escolar Office Brasil | Lepok Papelaria",
    category: "Case",
    description: "Filme produzido para a Escolar Office Brasil, como parte da série \"Escolar pelo Brasil\", onde acompanhamos a rotina e contamos a história da papelaria Lepok, localizada em São Paulo.",
    image: "https://i.ytimg.com/vi/rGk75VaxOHA/maxresdefault.jpg",
    videoId: "rGk75VaxOHA",
  },
  {
    title: "Construtora Equilíbrio | Blanc de Rouge",
    category: "Evento Corporativo",
    description: "Cobertura do evento de lançamento do Blanc de Rouge, residencial da Construtora Equilíbrio, que atua há mais de 50 anos em Curitiba e região.",
    image: "https://i.ytimg.com/vi/ipRxXf7od5E/maxresdefault.jpg",
    videoId: "ipRxXf7od5E",
  },
  {
    title: "ENAF | Congresso Brasileiro de Musculação",
    category: "Evento Corporativo",
    description: "Filme produzido para a ENAF durante o Congresso Brasileiro de Musculação que reuniu profissionais, atletas e entusiastas do mundo fitness em Curitiba.",
    image: "https://i.ytimg.com/vi/NSaibgM86dY/maxresdefault.jpg",
    videoId: "NSaibgM86dY",
  },
  {
    title: "Lumicenter | Essência Lumicenter",
    category: "Evento Corporativo",
    description: "Filme produzido para o evento Essência Lumicenter 2024 da Lumicenter Lighting, fabricante de produtos de iluminação, realizado em São José dos Pinhais.",
    image: "https://i.ytimg.com/vi/ond_kR7F_7s/maxresdefault.jpg",
    videoId: "ond_kR7F_7s",
  },
  {
    title: "LJ Santos",
    category: "Institucional",
    description: "Filme institucional produzido para a LJ Santos, empresa especializada em soluções industriais sustentáveis, com foco em tratamento de efluentes e equipamentos sob medida.",
    image: "https://i.ytimg.com/vi/Qjciy6xLVsk/maxresdefault.jpg",
    videoId: "Qjciy6xLVsk",
  },
  {
    title: "Congemas",
    category: "Evento Corporativo",
    description: "Filme produzido durante o 23º Encontro Regional do Colegiado Nacional de Gestores Municipais de Assistência Social (Congemas), evento realizado pelo Governo Federal em Florianópolis.",
    image: "https://i.ytimg.com/vi/Dm7kuEJ-McY/maxresdefault.jpg",
    videoId: "Dm7kuEJ-McY",
  },
  {
    title: "Dufrio | Energia Solar",
    category: "Produto",
    description: "Filme produzido para a Dufrio, empresa de refrigeração com mais de 25 anos, divulgando as soluções renováveis de sua linha de energia solar.",
    image: "https://i.ytimg.com/vi/eGiFbkpiH0Q/maxresdefault.jpg",
    videoId: "eGiFbkpiH0Q",
  },
  {
    title: "LJ Santos | Feira da Metalurgia",
    category: "Evento Corporativo",
    description: "Filme produzido para a LJ Santos durante a Feira da Metalurgia 2023, que reuniu mais de 12 mil visitantes em Joinville.",
    image: "https://i.ytimg.com/vi/foKTC-e29w8/maxresdefault.jpg",
    videoId: "foKTC-e29w8",
  },
  {
    title: "Action COACH",
    category: "Institucional",
    description: "Filme institucional produzido para a Action Coach, uma das maiores franquias de consultoria empresarial do mundo, presente em mais de 80 países.",
    image: "https://i.ytimg.com/vi/Roo1OWxkCZM/maxresdefault.jpg",
    videoId: "Roo1OWxkCZM",
  },
  {
    title: "Motin Films | Nescau",
    category: "Produto",
    description: "Filme produzido pela Motin Films para destacar os atributos do cereal Nescau em diversos ângulos.",
    image: "https://i.ytimg.com/vi/oD1ITLt8SP4/maxresdefault.jpg",
    videoId: "oD1ITLt8SP4",
  },
  {
    title: "Compwire | Confraternização",
    category: "Evento Corporativo",
    description: "Cobertura da confraternização de final de ano da Compwire, empresa especializada em soluções de TI, com foco em data centers, redes e armazenamento.",
    image: "https://i.ytimg.com/vi/zHyHZ2QnBjg/maxresdefault.jpg",
    videoId: "zHyHZ2QnBjg",
  },
  {
    title: "Hogrefe Construtora | Beach World Residences",
    category: "Produto",
    description: "Filme produzido para o pré-lançamento do empreendimento Beach World Residences da Hogrefe Construtora em Penha, no litoral catarinense, destacando seus diferenciais.",
    image: "https://i.ytimg.com/vi/C4V_BwMlKE0/maxresdefault.jpg",
    videoId: "C4V_BwMlKE0",
  },
  {
    title: "Francal Feiras",
    category: "Ação de Marketing",
    description: "Filme para divulgar o rebranding da Francal Feiras, uma das maiores produtoras de eventos de negócios do Brasil, com mais de 50 anos de atuação.",
    image: "https://i.ytimg.com/vi/WMFSuFo6iAA/maxresdefault.jpg",
    videoId: "WMFSuFo6iAA",
  },
  {
    title: "Flash Construtora",
    category: "Produto",
    description: "Filme produzido para a Flash Construtora, detalhando um imóvel de alto padrão localizado no bairro Santa Felicidade, em Curitiba.",
    image: "https://i.ytimg.com/vi/67FQ4Isw2tM/maxresdefault.jpg",
    videoId: "67FQ4Isw2tM",
  },
  {
    title: "Händz",
    category: "Produto",
    description: "Filme produto com modelagem 3D para a empresa curitibana Händz, divulgando o headphone EcoSound, fabricado com fibras de trigo e ABS.",
    image: "https://i.ytimg.com/vi/oC-T7m3JU8E/maxresdefault.jpg",
    videoId: "oC-T7m3JU8E",
  },
  {
    title: "LJ Santos | Estação de Tratamento de Efluentes",
    category: "Produto",
    description: "Filme produzido para a LJ Santos, divulgando suas estações de tratamento de efluentes industriais, destacando seus diferenciais e benefícios.",
    image: "https://i.ytimg.com/vi/4LE6PpXeUnQ/maxresdefault.jpg",
    videoId: "4LE6PpXeUnQ",
  },
  {
    title: "CW Trends",
    category: "Institucional",
    description: "Filme institucional produzido para a CW Trends, uma das empresas de maior destaque no ramo de venda de suplementos em Curitiba.",
    image: "https://i.ytimg.com/vi/XHPNutOOTQo/maxresdefault.jpg",
    videoId: "XHPNutOOTQo",
  },
  {
    title: "Naport",
    category: "Produto",
    description: "Filme produzido para divulgar o projeto de portas seccionadas automáticas desenvolvido pela Naport para o Yachthouse Residence Club em Balneário Camboriú.",
    image: "https://i.ytimg.com/vi/LgXxgTIMjmY/maxresdefault.jpg",
    videoId: "LgXxgTIMjmY",
  },
  {
    title: "Compwire",
    category: "Case",
    description: "Depoimento com Marcos Choinski, sócio fundador da Compwire, empresa especializada em soluções de TI, para o mercado internacional.",
    image: "https://i.ytimg.com/vi/ENuvzngBuK4/maxresdefault.jpg",
    videoId: "ENuvzngBuK4",
  },
  {
    title: "PesadosWEB | Master Trader",
    category: "Evento Corporativo",
    description: "Filme produzido para a PesadosWEB, empresa fundada por Wanderlei Silva, durante os bastidores de sua participação no evento Master Trader.",
    image: "https://i.ytimg.com/vi/rQci5PHwSAA/maxresdefault.jpg",
    videoId: "rQci5PHwSAA",
  },
  {
    title: "Vila Yamon",
    category: "Institucional",
    description: "Filme institucional produzido para o Vila Yamon, um dos bares mais requisitados de Curitiba, destacando a versatilidade e infraestrutura do estabelecimento.",
    image: "https://i.ytimg.com/vi/JjBw2zdNuek/maxresdefault.jpg",
    videoId: "JjBw2zdNuek",
  },
  {
    title: "Thiago Castelli | Marcando Meu Gado",
    category: "Artistas",
    description: "Videoclipe do artista curitibano Thiago Castelli para a música \"Marcando Meu Gado\".",
    image: "https://i.ytimg.com/vi/5xTvnW6of2o/maxresdefault.jpg",
    videoId: "5xTvnW6of2o",
  },
  {
    title: "CW Trends | Felipe Franco",
    category: "Ação de Marketing",
    description: "Cobertura de uma ação de marketing realizada pela loja de suplementos CWTrends com o fisiculturista Felipe Franco.",
    image: "https://i.ytimg.com/vi/2r1PhYSU5hY/maxresdefault.jpg",
    videoId: "2r1PhYSU5hY",
  },
  {
    title: "Ruan Mansur",
    category: "Artistas",
    description: "Gravação do DVD \"Violada do Mansur\" do artista curitibano de sertanejo Ruan Mansur.",
    image: "https://i.ytimg.com/vi/N_Lj-2hQIZc/maxresdefault.jpg",
    videoId: "N_Lj-2hQIZc",
  },
  {
    title: "Thiago Castelli | Costelada da Agronomia",
    category: "Artistas",
    description: "Apresentação do cantor curitibano Thiago Castelli durante sua participação na festa universitária Costelada da Agronomia.",
    image: "https://i.ytimg.com/vi/qy5XkX6wrwg/maxresdefault.jpg",
    videoId: "qy5XkX6wrwg",
  },
  {
    title: "Fresno",
    category: "Artistas",
    description: "Filme divulgando o show da Banda Fresno na Ópera de Arame, em Curitiba.",
    image: "https://i.ytimg.com/vi/2VcVx8T93cY/maxresdefault.jpg",
    videoId: "2VcVx8T93cY",
  },
  {
    title: "Action Coach",
    category: "Conteúdo",
    description: "Filme voltado para a venda de franquias da ActionCoach, uma das maiores consultorias empresariais do mundo, presente em mais de 80 países.",
    image: "https://i.ytimg.com/vi/XauRtG4ALys/maxresdefault.jpg",
    videoId: "XauRtG4ALys",
  },
  {
    title: "DJ CZ",
    category: "Artistas",
    description: "Filme para divulgação de evento do DJ CZ, um dos maiores nomes do funk e megafunk de Curitiba, durante participação na Violada do Mansur.",
    image: "https://i.ytimg.com/vi/Te02nXKzfOA/maxresdefault.jpg",
    videoId: "Te02nXKzfOA",
  },
  {
    title: "The Batman",
    category: "Ação de Marketing",
    description: "Filme divulgando uma ação promocional da Warner Bros Pictures para o lançamento do filme \"The Batman\" em uma hamburgueria de Curitiba.",
    image: "https://i.ytimg.com/vi/3VHmQY5Ak90/maxresdefault.jpg",
    videoId: "3VHmQY5Ak90",
  },
  {
    title: "Shot Time",
    category: "Ação de Marketing",
    description: "Filme produzido para o Shot Time, bar de shots localizado no Vila Yamon, em Curitiba.",
    image: "https://i.ytimg.com/vi/pavAz8vN4DY/maxresdefault.jpg",
    videoId: "pavAz8vN4DY",
  },
  {
    title: "Ruan Mansur | Shed",
    category: "Artistas",
    description: "Apresentação do cantor curitibano Ruan Mansur na casa de eventos Shed.",
    image: "https://i.ytimg.com/vi/QQYqNDKLaQs/maxresdefault.jpg",
    videoId: "QQYqNDKLaQs",
  },
  {
    title: "CW Trends | Felipe Donatto",
    category: "Evento Corporativo",
    description: "Cobertura de workshop promovido pela CWTrends, com a presença do nutricionista esportivo Felipe Donatto.",
    image: "https://i.ytimg.com/vi/AZ40lXILG2Q/maxresdefault.jpg",
    videoId: "AZ40lXILG2Q",
  },
  {
    title: "CW Trends",
    category: "Ação de Marketing",
    description: "Ação de marketing gravada em uma academia para a CWTrends, loja referência na venda de suplementos alimentares.",
    image: "https://i.ytimg.com/vi/zH3rERJkmRI/maxresdefault.jpg",
    videoId: "zH3rERJkmRI",
  },
  {
    title: "Ghostbusters: Mais Além",
    category: "Ação de Marketing",
    description: "Cobertura de uma ação de marketing da Sony Pictures para divulgação do filme Ghostbusters: Mais Além, em um cinema de Curitiba.",
    image: "https://i.ytimg.com/vi/0-CXPK2MlWI/maxresdefault.jpg",
    videoId: "0-CXPK2MlWI",
  },
  {
    title: "Favretto Mídia Exterior | LED 3D",
    category: "Produto",
    description: "Filme produzido para a Favretto Mídia Exterior para divulgação de seu painel de LED 3D em Itapema.",
    image: "https://i.ytimg.com/vi/-afHOczVR38/maxresdefault.jpg",
    videoId: "-afHOczVR38",
  },
  {
    title: "Gards",
    category: "Institucional",
    description: "Filme institucional produzido para o bar curitibano Gards, destacando sua atmosfera e estrutura.",
    image: "https://i.ytimg.com/vi/5_nDj1d2tyw/maxresdefault.jpg",
    videoId: "5_nDj1d2tyw",
  },
  {
    title: "Motin Films | Tanqueray",
    category: "Produto",
    description: "Filme produzido pela Motin Films para destacar os atributos do gim Tanqueray em takes dinâmicos e ângulos diferenciados.",
    image: "https://i.ytimg.com/vi/eBuo2rlB9mo/maxresdefault.jpg",
    videoId: "eBuo2rlB9mo",
  }
];

export const categories = [
  "Todos",
  "Institucional", 
  "Evento Corporativo",
  "Produto",
  "Case",
  "Conteúdo",
  "Ação de Marketing",
  "Artistas",
  "Treinamento"
];
